controller:
  manager:
    globalTransformationOptions:
      excludeRaw: true

defaultVaultConnection:
  enabled: true
  address: http://vault.mini-platform.svc.cluster.local:8200
  skipTLSVerify: false

defaultAuthMethod:
  enabled: true
  namespace: mini-platform
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: mini-platform
    serviceAccount: vault-auth
    tokenAudiences:
      - vault
