image:
  repository: robustadev/holmes
  tag: 0.38.2
  pullPolicy: IfNotPresent

holmes:
  url: http://holmes-holmes.mini-platform.svc.cluster.local/api/chat
  apiKeySecret:
    name: holmes-api
    key: HOLMES_API_KEY

service:
  port: 8080

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
