{{- range .Values.vaultSecrets.names }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ . }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  vaultAuthRef: {{ $.Values.vaultSecrets.vaultAuthRef }}
  type: kv-v2
  mount: {{ $.Values.vaultSecrets.mount }}
  path: {{ . }}
  refreshAfter: {{ $.Values.vaultSecrets.refreshAfter }}
  destination:
    name: {{ . }}
    create: true
    overwrite: true
{{- end }}
